export const path = {
  home: '/',
  aboutUs: '/about-us',
  createWork: '/:type/create',

  login: '/login',
  comic: 'comic',
  novel: 'novel',
  myPage: '/my-page',
  payment: '/payment',
  detailWork: '/:type/:id/detail',
  updateWork: '/:type/:id/update',
  detailEpisode: '/:type/:id/detail/episode',
  detailNotice: '/:type/:id/detail/notice',
  createEpisode: '/:type/:id/episode/create',
  updateEpisode: '/:type/:id/episode/:epId/update',
  createNotice: '/:type/:id/notice/create',
  updateNotice: '/:type/:id/notice/update/:uuid',
  notice: '/notice',
  all: '*',
};
